version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sftp_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   
      - "15672:15672" 

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000" 
      - "9001:9001" 
    volumes:
      - minio_data:/data

  sftp:
    image: atmoz/sftp
    restart: always
    environment:
      SFTP_USERS: "foo:pass:::upload"
    ports:
      - "2222:22"

  web:  
    image: sftptominiouploader:latest
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq
      - redis
      - minio
      - sftp
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  celery:
    image: sftptominiouploader:latest
    command: celery -A src.celery_worker.celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - web
      - postgres
      - rabbitmq
      - redis
      - minio
      - sftp

  celery-beat:
    image: sftptominiouploader:latest
    command: celery -A src.celery_worker.celery_app beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - web
      - postgres
      - rabbitmq
      - redis
      - minio
      - sftp

volumes:
  postgres_data:
  minio_data:
  sftp_data:

